version: '3.9'

services:
  wazuh:
    image: wazuh/wazuh:latest
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh_data:/var/ossec/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:55000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  wazuh_data:
